/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppContactRouteImport } from './routes/app.contact'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppBatchRouteImport } from './routes/app.batch'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AppBatchIndexRouteImport } from './routes/app.batch.index'
import { Route as AppJobsJobIdRouteImport } from './routes/app.jobs.$jobId'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app.documents.$documentId'
import { Route as AppBatchBatchIdRouteImport } from './routes/app.batch.$batchId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchRoute = AppBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchIndexRoute = AppBatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBatchRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchBatchIdRoute = AppBatchBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => AppBatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/audit': typeof AppAuditRoute
  '/app/batch': typeof AppBatchRouteWithChildren
  '/app/compare': typeof AppCompareRoute
  '/app/contact': typeof AppContactRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/batch/$batchId': typeof AppBatchBatchIdRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/batch/': typeof AppBatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/about': typeof AppAboutRoute
  '/app/audit': typeof AppAuditRoute
  '/app/compare': typeof AppCompareRoute
  '/app/contact': typeof AppContactRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/app/batch/$batchId': typeof AppBatchBatchIdRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/batch': typeof AppBatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/audit': typeof AppAuditRoute
  '/app/batch': typeof AppBatchRouteWithChildren
  '/app/compare': typeof AppCompareRoute
  '/app/contact': typeof AppContactRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/batch/$batchId': typeof AppBatchBatchIdRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/batch/': typeof AppBatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/app/about'
    | '/app/audit'
    | '/app/batch'
    | '/app/compare'
    | '/app/contact'
    | '/app/settings'
    | '/app/upload'
    | '/auth/login'
    | '/auth/register'
    | '/share/$token'
    | '/app/'
    | '/app/batch/$batchId'
    | '/app/documents/$documentId'
    | '/app/jobs/$jobId'
    | '/app/batch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app/about'
    | '/app/audit'
    | '/app/compare'
    | '/app/contact'
    | '/app/settings'
    | '/app/upload'
    | '/auth/login'
    | '/auth/register'
    | '/share/$token'
    | '/app'
    | '/app/batch/$batchId'
    | '/app/documents/$documentId'
    | '/app/jobs/$jobId'
    | '/app/batch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/app/about'
    | '/app/audit'
    | '/app/batch'
    | '/app/compare'
    | '/app/contact'
    | '/app/settings'
    | '/app/upload'
    | '/auth/login'
    | '/auth/register'
    | '/share/$token'
    | '/app/'
    | '/app/batch/$batchId'
    | '/app/documents/$documentId'
    | '/app/jobs/$jobId'
    | '/app/batch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batch': {
      id: '/app/batch'
      path: '/batch'
      fullPath: '/app/batch'
      preLoaderRoute: typeof AppBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batch/': {
      id: '/app/batch/'
      path: '/'
      fullPath: '/app/batch/'
      preLoaderRoute: typeof AppBatchIndexRouteImport
      parentRoute: typeof AppBatchRoute
    }
    '/app/jobs/$jobId': {
      id: '/app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batch/$batchId': {
      id: '/app/batch/$batchId'
      path: '/$batchId'
      fullPath: '/app/batch/$batchId'
      preLoaderRoute: typeof AppBatchBatchIdRouteImport
      parentRoute: typeof AppBatchRoute
    }
  }
}

interface AppBatchRouteChildren {
  AppBatchBatchIdRoute: typeof AppBatchBatchIdRoute
  AppBatchIndexRoute: typeof AppBatchIndexRoute
}

const AppBatchRouteChildren: AppBatchRouteChildren = {
  AppBatchBatchIdRoute: AppBatchBatchIdRoute,
  AppBatchIndexRoute: AppBatchIndexRoute,
}

const AppBatchRouteWithChildren = AppBatchRoute._addFileChildren(
  AppBatchRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBatchRoute: typeof AppBatchRouteWithChildren
  AppCompareRoute: typeof AppCompareRoute
  AppContactRoute: typeof AppContactRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAuditRoute: AppAuditRoute,
  AppBatchRoute: AppBatchRouteWithChildren,
  AppCompareRoute: AppCompareRoute,
  AppContactRoute: AppContactRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
